package demo.repository;

import demo.entity.Client;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

//This will be auto implemented by Spring and will provide an implementation for the CRUD operations
//CRUD = Create, Read, Update, Delete

//This interface is bean = an object that is instantiated, assembled and managed by Spring
@Repository
public interface ClientRepository extends CrudRepository<Client,Integer> {

    //we don't need to define this search query because it uses the identity attribute of class Client and is
    //auto-generated because ClientRepository extends CrudRepository

    //Optional<Client> findById(Integer id);

    //"findBy" - is one of the most used prefixes for creating derived query methods for search queries
    //because the attribute name is not the identity attribute (and the primary key of the table)
    Optional<Client> findByFirstName(String firstName);

    //"delete" - the delete method always returns void and receives as parameter the object to be deleted,
    //in this case, a Client object
    //The delete method that receives the object to be deleted is always autogenerated in the CRUD repository
    //void delete(Client client);






}
